version: "3.3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'blogapplication'
      MYSQL_USER: 'dockeruser'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
     - my-db:/var/lib/mysql
volumes:
  my-db:



     